import type { CategoryGroup, Venue, ExternalVenue } from "./types";

export const categoryGroups: CategoryGroup[] = [
  {
    name: "MPK",
    items: [
      { name: "Charity", color: "#93c5fd", textColor: "#1e3a8a" },
      { name: "Food Delivery", color: "#3b82f6", textColor: "#fff" },
      { name: "Holiday/Travel", color: "#2563eb", textColor: "#fff" },
      { name: "Health Agency", color: "#1d4ed8", textColor: "#fff" },
    ],
  },
  {
    name: "Promo",
    items: [
      { name: "Dog Care", color: "#fdba74", textColor: "#7c2d12" },
      { name: "Furniture", color: "#fb923c", textColor: "#fff" },
      { name: "Motor/Driving", color: "#f97316", textColor: "#fff" },
      { name: "Utilities", color: "#ea580c", textColor: "#fff" },
      { name: "Experience Days", color: "#c2410c", textColor: "#fff" },
    ],
  },
  {
    name: "Retail",
    items: [
      { name: "Art Prints", color: "#fda4af", textColor: "#881337" },
      { name: "Bakery", color: "#fb7185", textColor: "#fff" },
      { name: "Clothing", color: "#e11d48", textColor: "#fff" },
      { name: "Cosmetics/Perfume", color: "#be123c", textColor: "#fff" },
    ],
  },
  {
    name: "RUPU",
    items: [
      { name: "Craft Markets", color: "#86efac", textColor: "#14532d" },
      { name: "Gifts", color: "#4ade80", textColor: "#14532d" },
      { name: "Hair Straighteners", color: "#22c55e", textColor: "#fff" },
      { name: "Mediterranean Food", color: "#16a34a", textColor: "#fff" },
      { name: "Vending", color: "#15803d", textColor: "#fff" },
    ],
  },
  {
    name: "Other",
    items: [
      { name: "Cars (Automotive)", color: "#d8b4fe", textColor: "#581c87" },
      { name: "Children's Rides", color: "#c084fc", textColor: "#fff" },
      { name: "Jewellery/Watches", color: "#a855f7", textColor: "#fff" },
      { name: "Other", color: "#7c3aed", textColor: "#fff" },
    ],
  },
];

export const venues: Venue[] = [
  {
    id: "v1",
    name: "The Centre",
    location: "Livingston",
    portfolio: "Scotland Centres",
    spaces: [
      {
        id: "s1",
        name: "C14 Promotional Kiosk",
        bookings: [
          {
            id: "BK-250110",
            customer: "Summer Fest Catering",
            department: "MPK",
            classification: "Food Delivery",
            status: "Finalised",
            salesperson: "Marc Rayton",
            primaryContact: "Jenny Mills",
            grossPrice: 1800.0,
            startDate: "2025-07-07",
            endDate: "2025-07-19",
            categoryGroup: "MPK",
            categoryItem: "Food Delivery",
          },
          {
            id: "BK-250215",
            customer: "Autumn Charity Drive",
            department: "MPK",
            classification: "Charity",
            status: "Confirmed",
            salesperson: "Sarah Wilson",
            primaryContact: "Peter Grant",
            grossPrice: 600.0,
            startDate: "2025-10-06",
            endDate: "2025-10-18",
            categoryGroup: "MPK",
            categoryItem: "Charity",
          },
          {
            id: "BK-260380",
            customer: "Croci Collective Ltd",
            department: "MPK",
            classification: "Food Delivery",
            status: "Finalised",
            salesperson: "Marc Rayton",
            primaryContact: "Nicola Thompson",
            grossPrice: 1200.0,
            startDate: "2026-02-02",
            endDate: "2026-02-14",
            categoryGroup: "MPK",
            categoryItem: "Food Delivery",
          },
          {
            id: "BK-260412",
            customer: "Blue Horizons Travel",
            department: "MPK",
            classification: "Holiday/Travel",
            status: "Confirmed",
            salesperson: "Marc Rayton",
            primaryContact: "James Cole",
            grossPrice: 2400.0,
            startDate: "2026-02-16",
            endDate: "2026-02-28",
            categoryGroup: "MPK",
            categoryItem: "Charity",
          },
          {
            id: "BK-260500",
            customer: "Fresh Bites Co",
            department: "MPK",
            classification: "Food Delivery",
            status: "Provisional",
            salesperson: "Sarah Wilson",
            primaryContact: "Tom Andrews",
            grossPrice: 800.0,
            startDate: "2026-04-13",
            endDate: "2026-04-25",
            categoryGroup: "MPK",
            categoryItem: "Food Delivery",
          },
          {
            id: "BK-260601",
            customer: "Green Paws Ltd",
            department: "Promo",
            classification: "Dog Care",
            status: "Finalised",
            salesperson: "Marc Rayton",
            primaryContact: "Lisa Chen",
            grossPrice: 1500.0,
            startDate: "2026-06-01",
            endDate: "2026-06-13",
            categoryGroup: "Promo",
            categoryItem: "Dog Care",
          },
        ],
        blackouts: [],
      },
      {
        id: "s2",
        name: "C16 East Court 2",
        bookings: [
          {
            id: "BK-250320",
            customer: "Spring Health Expo",
            department: "MPK",
            classification: "Health Agency",
            status: "Finalised",
            salesperson: "Sarah Wilson",
            primaryContact: "Karen Yates",
            grossPrice: 2100.0,
            startDate: "2025-03-10",
            endDate: "2025-03-22",
            categoryGroup: "MPK",
            categoryItem: "Health Agency",
          },
          {
            id: "BK-260701",
            customer: "Sunrise Health",
            department: "MPK",
            classification: "Health Agency",
            status: "Confirmed",
            salesperson: "Sarah Wilson",
            primaryContact: "David Park",
            grossPrice: 3200.0,
            startDate: "2026-02-16",
            endDate: "2026-03-07",
            categoryGroup: "MPK",
            categoryItem: "Health Agency",
          },
          {
            id: "BK-260715",
            customer: "Motor World Events",
            department: "Promo",
            classification: "Motor/Driving",
            status: "Finalised",
            salesperson: "Marc Rayton",
            primaryContact: "Helen Brooks",
            grossPrice: 1800.0,
            startDate: "2026-06-15",
            endDate: "2026-06-27",
            categoryGroup: "Promo",
            categoryItem: "Motor/Driving",
          },
        ],
        blackouts: [
          {
            reason: "Venue refurbishment",
            startDate: "2026-04-06",
            endDate: "2026-04-19",
            addedBy: "Marc Rayton",
          },
        ],
      },
      {
        id: "s3",
        name: "C11 P3 - B&M",
        bookings: [
          {
            id: "BK-260801",
            customer: "Sparkle Cosmetics",
            department: "Retail",
            classification: "Cosmetics/Perfume",
            status: "Finalised",
            salesperson: "Sarah Wilson",
            primaryContact: "Amy Foster",
            grossPrice: 950.0,
            startDate: "2026-02-02",
            endDate: "2026-02-21",
            categoryGroup: "Retail",
            categoryItem: "Cosmetics/Perfume",
          },
          {
            id: "BK-260802",
            customer: "Charity Aid Foundation",
            department: "MPK",
            classification: "Charity",
            status: "Provisional",
            salesperson: "Marc Rayton",
            primaryContact: "Rachel Green",
            grossPrice: 450.0,
            startDate: "2026-02-23",
            endDate: "2026-03-07",
            categoryGroup: "MPK",
            categoryItem: "Charity",
          },
          {
            id: "BK-260803",
            customer: "Quick Snacks Ltd",
            department: "MPK",
            classification: "Food Delivery",
            status: "Confirmed",
            salesperson: "Sarah Wilson",
            primaryContact: "Mike Brown",
            grossPrice: 600.0,
            startDate: "2026-03-23",
            endDate: "2026-04-04",
            categoryGroup: "MPK",
            categoryItem: "Food Delivery",
          },
          {
            id: "BK-260804",
            customer: "Adventure Experiences",
            department: "Promo",
            classification: "Experience Days",
            status: "Finalised",
            salesperson: "Marc Rayton",
            primaryContact: "Dan White",
            grossPrice: 2800.0,
            startDate: "2026-07-20",
            endDate: "2026-08-15",
            categoryGroup: "Promo",
            categoryItem: "Experience Days",
          },
          {
            id: "BK-260805",
            customer: "Autumn Bakery",
            department: "Retail",
            classification: "Bakery",
            status: "Confirmed",
            salesperson: "Sarah Wilson",
            primaryContact: "Ella Stone",
            grossPrice: 1100.0,
            startDate: "2026-11-02",
            endDate: "2026-11-14",
            categoryGroup: "Retail",
            categoryItem: "Bakery",
          },
          {
            id: "BK-260806",
            customer: "Winter Gifts Co",
            department: "RUPU",
            classification: "Gifts",
            status: "Provisional",
            salesperson: "Marc Rayton",
            primaryContact: "Zoe Clarke",
            grossPrice: 1600.0,
            startDate: "2026-12-14",
            endDate: "2026-12-26",
            categoryGroup: "RUPU",
            categoryItem: "Gifts",
          },
        ],
        blackouts: [],
      },
    ],
  },
  {
    id: "v2",
    name: "Meadowhall",
    location: "Sheffield",
    portfolio: "Yorkshire Centres",
    spaces: [
      {
        id: "s4",
        name: "Unit 1 - Main Hall",
        bookings: [
          {
            id: "BK-260901",
            customer: "City Furniture Expo",
            department: "Promo",
            classification: "Furniture",
            status: "Finalised",
            salesperson: "Marc Rayton",
            primaryContact: "Kevin Hall",
            grossPrice: 4500.0,
            startDate: "2026-03-02",
            endDate: "2026-03-21",
            categoryGroup: "Promo",
            categoryItem: "Furniture",
          },
          {
            id: "BK-260902",
            customer: "Utility Deals UK",
            department: "Promo",
            classification: "Utilities",
            status: "Confirmed",
            salesperson: "Sarah Wilson",
            primaryContact: "Ian Cross",
            grossPrice: 2200.0,
            startDate: "2026-06-15",
            endDate: "2026-06-27",
            categoryGroup: "Promo",
            categoryItem: "Utilities",
          },
          {
            id: "BK-260903",
            customer: "Xmas Market Traders",
            department: "RUPU",
            classification: "Craft Markets",
            status: "Provisional",
            salesperson: "Marc Rayton",
            primaryContact: "Paula Dean",
            grossPrice: 3800.0,
            startDate: "2026-11-30",
            endDate: "2026-12-12",
            categoryGroup: "RUPU",
            categoryItem: "Craft Markets",
          },
          {
            id: "BK-270101",
            customer: "New Year Furniture Fair",
            department: "Promo",
            classification: "Furniture",
            status: "Provisional",
            salesperson: "Marc Rayton",
            primaryContact: "Kevin Hall",
            grossPrice: 5000.0,
            startDate: "2027-02-01",
            endDate: "2027-02-13",
            categoryGroup: "Promo",
            categoryItem: "Furniture",
          },
        ],
        blackouts: [],
      },
      {
        id: "s5",
        name: "Kiosk K3 - Food Court",
        bookings: [
          {
            id: "BK-261001",
            customer: "Mediterranean Feast",
            department: "RUPU",
            classification: "Mediterranean Food",
            status: "Finalised",
            salesperson: "Sarah Wilson",
            primaryContact: "Maria Costa",
            grossPrice: 900.0,
            startDate: "2026-02-23",
            endDate: "2026-03-07",
            categoryGroup: "RUPU",
            categoryItem: "Mediterranean Food",
          },
        ],
        blackouts: [],
      },
    ],
  },
  {
    id: "v3",
    name: "Arndale Centre",
    location: "Manchester",
    portfolio: "North West Centres",
    spaces: [
      {
        id: "s6",
        name: "Unit A2 - Ground Floor",
        bookings: [
          {
            id: "BK-261101",
            customer: "Style Avenue",
            department: "Retail",
            classification: "Clothing",
            status: "Finalised",
            salesperson: "Marc Rayton",
            primaryContact: "Sophie Lang",
            grossPrice: 2600.0,
            startDate: "2026-03-09",
            endDate: "2026-03-28",
            categoryGroup: "Retail",
            categoryItem: "Clothing",
          },
          {
            id: "BK-261102",
            customer: "Art House Prints",
            department: "Retail",
            classification: "Art Prints",
            status: "Confirmed",
            salesperson: "Sarah Wilson",
            primaryContact: "Ben Taylor",
            grossPrice: 750.0,
            startDate: "2026-05-04",
            endDate: "2026-05-16",
            categoryGroup: "Retail",
            categoryItem: "Art Prints",
          },
          {
            id: "BK-270201",
            customer: "Spring Fashion Pop-Up",
            department: "Retail",
            classification: "Clothing",
            status: "Confirmed",
            salesperson: "Marc Rayton",
            primaryContact: "Sophie Lang",
            grossPrice: 3100.0,
            startDate: "2027-04-05",
            endDate: "2027-04-19",
            categoryGroup: "Retail",
            categoryItem: "Clothing",
          },
        ],
        blackouts: [],
      },
      {
        id: "s7",
        name: "Kiosk B1 - Level 2",
        bookings: [
          {
            id: "BK-261201",
            customer: "Hair Pro UK",
            department: "RUPU",
            classification: "Hair Straighteners",
            status: "Finalised",
            salesperson: "Marc Rayton",
            primaryContact: "Claire Adams",
            grossPrice: 1400.0,
            startDate: "2026-04-06",
            endDate: "2026-04-18",
            categoryGroup: "RUPU",
            categoryItem: "Hair Straighteners",
          },
          {
            id: "BK-261202",
            customer: "Fun Fair Rides Ltd",
            department: "Other",
            classification: "Children's Rides",
            status: "Provisional",
            salesperson: "Sarah Wilson",
            primaryContact: "Gary Nolan",
            grossPrice: 5200.0,
            startDate: "2026-07-06",
            endDate: "2026-08-01",
            categoryGroup: "Other",
            categoryItem: "Children's Rides",
          },
        ],
        blackouts: [
          {
            reason: "Electrical maintenance",
            startDate: "2026-09-07",
            endDate: "2026-09-19",
            addedBy: "Sarah Wilson",
          },
        ],
      },
      {
        id: "s8",
        name: "Stand C5 - Food Hall",
        bookings: [
          {
            id: "BK-261301",
            customer: "Vend-O-Matic",
            department: "RUPU",
            classification: "Vending",
            status: "Confirmed",
            salesperson: "Marc Rayton",
            primaryContact: "Nick Ford",
            grossPrice: 680.0,
            startDate: "2026-02-09",
            endDate: "2026-02-21",
            categoryGroup: "RUPU",
            categoryItem: "Vending",
          },
          {
            id: "BK-261302",
            customer: "Jewel Box Events",
            department: "Other",
            classification: "Jewellery/Watches",
            status: "Finalised",
            salesperson: "Sarah Wilson",
            primaryContact: "Olivia Shaw",
            grossPrice: 3400.0,
            startDate: "2026-06-01",
            endDate: "2026-06-20",
            categoryGroup: "Other",
            categoryItem: "Jewellery/Watches",
          },
        ],
        blackouts: [],
      },
    ],
  },
];

export const externalVenue: ExternalVenue = {
  id: "ev1",
  name: "Lakeside Retail Park",
  spaces: [
    {
      id: "es1",
      name: "Unit 4A (Mall Entrance)",
      bookings: [
        {
          id: "BK-260150",
          customer: "Healthy Bites Market",
          department: "RUPU",
          classification: "Mediterranean Food",
          status: "Confirmed",
          salesperson: "Marc Rayton",
          primaryContact: "Laura Simms",
          grossPrice: 1200.0,
          startDate: "2026-02-09",
          endDate: "2026-02-21",
          categoryGroup: "RUPU",
          categoryItem: "Mediterranean Food",
        },
        {
          id: "BK-260220",
          customer: "TravelBright",
          department: "MPK",
          classification: "Holiday/Travel",
          status: "Provisional",
          salesperson: "Marc Rayton",
          primaryContact: "Jo Peters",
          grossPrice: 2800.0,
          startDate: "2026-04-13",
          endDate: "2026-04-22",
          categoryGroup: "MPK",
          categoryItem: "Holiday/Travel",
        },
        {
          id: "BK-260340",
          customer: "Green Living Expo",
          department: "Promo",
          classification: "Utilities",
          status: "Confirmed",
          salesperson: "Sarah Wilson",
          primaryContact: "Sam Greaves",
          grossPrice: 3500.0,
          startDate: "2026-07-13",
          endDate: "2026-08-01",
          categoryGroup: "Promo",
          categoryItem: "Utilities",
        },
      ],
      blackouts: [],
    },
    {
      id: "es2",
      name: "Unit 4B (Food Court)",
      bookings: [
        {
          id: "BK-260410",
          customer: "Fresh & Fast Catering",
          department: "MPK",
          classification: "Food Delivery",
          status: "Confirmed",
          salesperson: "Sarah Wilson",
          primaryContact: "Kate Brennan",
          grossPrice: 1800.0,
          startDate: "2026-03-02",
          endDate: "2026-03-21",
          categoryGroup: "MPK",
          categoryItem: "Food Delivery",
        },
        {
          id: "BK-270050",
          customer: "Winter Warmers Ltd",
          department: "MPK",
          classification: "Food Delivery",
          status: "Confirmed",
          salesperson: "Marc Rayton",
          primaryContact: "Dave Harlow",
          grossPrice: 1400.0,
          startDate: "2027-01-05",
          endDate: "2027-01-17",
          categoryGroup: "MPK",
          categoryItem: "Food Delivery",
        },
      ],
      blackouts: [],
    },
    {
      id: "es3",
      name: "Kiosk K1",
      bookings: [
        {
          id: "BK-260510",
          customer: "Bright Sparks Toys",
          department: "Retail",
          classification: "Gifts",
          status: "Provisional",
          salesperson: "Marc Rayton",
          primaryContact: "Fiona Trent",
          grossPrice: 900.0,
          startDate: "2026-02-02",
          endDate: "2026-02-11",
          categoryGroup: "RUPU",
          categoryItem: "Gifts",
        },
        {
          id: "BK-260610",
          customer: "Petal & Bloom",
          department: "Retail",
          classification: "Gifts",
          status: "Confirmed",
          salesperson: "Sarah Wilson",
          primaryContact: "Rosie Watts",
          grossPrice: 650.0,
          startDate: "2026-05-25",
          endDate: "2026-05-30",
          categoryGroup: "RUPU",
          categoryItem: "Gifts",
        },
      ],
      blackouts: [
        {
          reason: "Kiosk refitting",
          startDate: "2026-08-17",
          endDate: "2026-09-05",
          addedBy: "Marc Rayton",
        },
      ],
    },
  ],
};
